[project]
name = "nextpass"
version = "0.1.0"
readme = "README.md"
description = "Modern Next.js password generator"
requires-python = ">=3.12"
dependencies = [
    "uvicorn (>=0.34.2,<0.35.0)",
    "fastapi (>=0.115.12,<0.116.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "nextpass"
version = "0.1.0"
readme = "README.md"
description = "Modern Next.js password generator"
authors = [
  "Mikhalkin Gregory <somokill650@gmail.com>"
]
package-mode = false
